### ISSUE TITLE
前回言われた画面のコードレビュー

### ISSUE THREAD

**Issue by taninao1122** [kiesproject/open_campus#1]
前回言われた画面を作成したが、初めてのこともありできているか不安なのでコードレビューをしてほしい

**Comment by Kusunoki-19** [comment]
改善としては<header>タグの中に主要なページコンテンツ(地図や教室を表示するsenciton)を入れるのは何か違和感を感じた
headerタグは次のような使用を想定していた
```
<header> <h1>ページタイトル</h1></header>
```
参考:(https://developer.mozilla.org/ja/docs/Web/HTML/Element/header#Examples)

また会議メモでも書かれた図のように
```
<header>
<section>
<section>
<footer>
```
のようにheaderとsection(そしてfooter)は同列になることを想定していた

```
こんな感じにしたかった
<div id="container">
 <header><h1>title</h1></header>
 <section></section>
 <section></section>
 <section></section>
 <footer></footer>
</div>
```
![image](https://user-images.githubusercontent.com/19787801/47067188-6e3d4e80-d223-11e8-8959-94974df6e09b.png)

それ以外の構造などについてはheaderにページタイトルを表示するくらいだと思う


```
今思えばこっちのほうがよかったかも
<header><h1>title</h1></header>
<div id="container">
 <section></section>
 <section></section>
 <section></section>
</div>
<footer></footer>
```

**Comment by taninao1122** [comment]
了解。ありがとう。修正しました
