### ISSUE TITLE
genzaichi_syutokuブランチのプログラムのバグがうまく治らない

### ISSUE THREAD

**Issue by taninao1122** [kiesproject/open_campus#14]
現状最初の最初の読み込みで初期位置を自分の位置、セレクトボックス内の値を変更するとそちらのマーカが立つという風にしたいのですが僕の力不足でうまくいかないので助言をいただきたいです、
理想は自分の位置は常に表示＋セレクトボックスで選んだ号館のマーカーを表示
みたいな感じです。

**Comment by Kusunoki-19** [comment]
まず、どこのファイルを使っていて、どこまで実現していて、どこがどのようにうまくいかないのか教えていただきたいです。
いまgenzaiti_syutoku.htmlを参照しているのですが、selectボックスを変更するとそこに応じた変更ができているように思いました。どこで行き詰っているのか詳しく教えてください。

**Comment by taninao1122** [comment]
choice_map/genzaiti_syutoku.htmlのファイルです。
どこまで実現したかは上記のとおりです。
どこがうまくいかないかは
最初のinitmap()で現在地を取得して次にセレクトボックスが変更されるとselectchangedのlatlngのリスト(63行目あたり)の値が読み込まれるのですがそれで画面が遷移したときに現在地を取得したマーカもなくならずに画面に表示するのを続けたいという感じです。
要は自分の位置は常に表示＋セレクトボックスで選んだ号館のマーカーを表示したいが、どうすればいいかがわからないという感じです。

**Comment by taninao1122** [comment]
できました。うおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおお

**Comment by taninao1122** [comment]
予想されるバグや不足しているセレクトボックスの数、JSの部分をファイルに移動などなるべく早めに終わらせておきます。
