### ISSUE TITLE
関連リンクとして何を出すかの質問

### ISSUE THREAD

**Issue by taninao1122** [kiesproject/open_campus#24]
関連リンクとして下記の画像のようにリンクを付けたのですがリンクを付けすぎても微妙な感じがするので"何のリンクを付けるか"のご意見をいただきたいです。

![image](https://user-images.githubusercontent.com/25599704/53323690-33aa9780-3922-11e9-881c-e8e16bf71fe3.png)

**Comment by Kusunoki-19** [comment]
微妙な感じがするのはリンクの数が問題ではなく、レイアウトの問題なのではと思いました。
個人的なfooterの定番はウィンドウwidth :100%、背景色は輝度が低い色(黒とか)、文字色が輝度高めの色(白とか)にするとおしゃれになると思います。またline-heightやpaddingなど余白を調整するとより高級感？(整ったイメージ)が出ます。
↓参考
![image](https://user-images.githubusercontent.com/19787801/53328351-19c28200-392d-11e9-9343-d313c7a3af1b.png)

画像を見た感じ、タイムテーブルセクションなどを同じようにsectionタグに作っているのではないかと思います。footerタグが現在あると思うので、そのwidthを100%にして、その中に作りこむと簡単かと思います。

**Comment by taninao1122** [comment]
footerに入れるかどうしようか判断して、セクションとして作ったっという感じです。
とりあえずフッターとして改めて作ります

**Comment by taninao1122** [comment]
こんな感じにしてみました。
関連リンクを中央寄せにしようか左寄せにしようかが迷いましたがどう思いますでしょうか？
![image](https://user-images.githubusercontent.com/25599704/53339257-3076d200-3949-11e9-9f5f-b318ebd71740.png)

**Comment by toipokun** [comment]
僕は左寄せのこのままのほうが良いと思います
