### ISSUE TITLE
フッターやヘッダーなどの修正

### ISSUE THREAD

**Issue by taninao1122** [kiesproject/open_campus#29]
### 概要
フッターやヘッダーの修正など
### タスク
- [x] オープンキャンパスの日にちをいれる
- [ ] headerの左にKIESロゴを追加
- [x] footerのリンクをセンターへ

**Comment by taninao1122** [comment]
うーんｗ
![image](https://user-images.githubusercontent.com/25599704/54014871-51e58280-41c1-11e9-8eef-f77cedc0ff23.png)

**Comment by taninao1122** [comment]
位置について質問なのですが日付の位置でどの位置が一番しっくりきますか？

![image](https://user-images.githubusercontent.com/25599704/54084687-3c19be00-4377-11e9-89a1-01773a789143.png)


![image](https://user-images.githubusercontent.com/25599704/54084654-cf062880-4376-11e9-9cf7-eb5bf6501844.png)

![image](https://user-images.githubusercontent.com/25599704/54084648-b4cc4a80-4376-11e9-8d40-7a65fa82c088.png)

**Comment by toipokun** [comment]
一番上かなぁ

**Comment by taninao1122** [comment]
了解
