### ISSUE TITLE
Sectionとかの質問です。

### ISSUE THREAD

**Issue by toipokun** [kiesproject/open_campus#4]
Sectionの意味がよくわかってないんだけど画像表示と各号館の一覧の表示ってSection分けた方がいいの？あと、各号館の一覧の表示はリスト表示でいいのかな？

Issuesっての使うの初めてなんでなんかよくないことしてたら言って下さい。

**Comment by Kusunoki-19** [comment]
号館の一覧は、テーブルやリストでの表示を考えていました。sectionの意味などは“html section 使い方“などで調べれば出てくると思います。一回作ってみてくれると、意見を言いやすいです。

**Comment by taninao1122** [comment]
issuesの使い方としてはとてもいいと思いますのでどんどんつかっていきましょう！
